---
title: "Python (Reticulate)"
output: 
  html_document:
    code_folding: show
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")

## Packages
library(reticulate)
library(tidyverse)
```

## Introduction

```{r, eval=FALSE}
# create a new environment 
conda_create("r-NLP")

# install modules
conda_install("r-NLP", c("scipy", "gensim", "networkx", "nltk", "numpy"))
```

```{r}
# indicate that we want to use a specific condaenv
use_condaenv(condaenv = "r-NLP")
```

- Access to objects created within Python chunks from R using the `py` object (e.g. `py$x` would access an `x` variable created within Python from R).

- Access to objects created within R chunks from Python using the `r` object (e.g. `r.x` would access to `x` variable created within R from Python).

```{python}
## Python chunk
a = [1, 2, 5, "a"]
```


```{r}
## R chunk
names(py$a) <- letters[1:4]
bind_rows(py$a)
```

```{python}
## Python chunk
a
```

```{r}
## R chunk
## import NumPy (it will be automatically discovered in "r-reticulate")
np <- import("numpy")
np$random$random(10L)
```

```{python}
## Python chunk
import numpy as np
b = np.identity(3)
b
b.shape
```

```{r}
## R chunk
py$b
dim(py$b)
```

```{python}
## Python chunk
[x**2 for x in range(10)]
[w for w in r.fruit if len(w) >= 12]
```

**Using Python functions**

```{python}
def flip(p):
    return np.random.random() < p
```


```{python}
flip(0.5)
```

```{r}
replicate(10, py$flip(0.3))
```

```{python}
def all_pairs(nodes):
    for i, u in enumerate(nodes):
        for j, v in enumerate(nodes):
            if i>j:
                yield u, v
                
def random_pairs(nodes, p):
    for edge in all_pairs(nodes):
        if flip(p):
            yield edge
            
import networkx as nx

def make_random_graph(n, p):
    G = nx.Graph()
    nodes = range(n)
    G.add_nodes_from(nodes)
    G.add_edges_from(random_pairs(nodes, p))
    return G
```

```{python}
G = make_random_graph(n = 30, p = 0.05)
G = nx.adjacency_matrix(G).asformat("array")
```

```{r}
library(ggraph)
py$G %>% 
  igraph::graph_from_adjacency_matrix(mode = "undirected") %>% 
  ggraph(layout = "nicely") +
  geom_edge_fan(alpha = 0.6) +
  geom_node_point(col = "steelblue1") +
  theme_graph()
```

