---
title: "Time"
output: 
  html_document:
    code_folding: show
    theme: paper
    toc: yes
    toc_float: 
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

How to think about time in statistics?

- Time as history, i.e. how circumstances change or stay the same over time.

- Time as before-and-after comparisons: i.e. how things change after some particular event takes place.

- Time as waiting for something to happen: also known as *survival analysis*, event history analysis, among other names.

- Time as a basis for prediction: use previous years to predict upcoming years.

- Time as reciprocal causation. Many processes seem like it's hard to figure out what causes what; thus, we try to get a leverage on the *order* of effects.

- Time as nuisance, or how to remove time from the data (e.g. We would really prefer 20 randomly-selected societies, but instead we have the same one society over 20 years).

## Essential packages

**Introduction to `lubridate` and `xts`**



## Forecasting


## Prophet


## Kalman filters


## Survival Analysis




